# Generated by Django 2.2.4 on 2020-04-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutorail_published',
            new_name='tutorial_published',
        ),
    ]
