# Generated by Django 2.2.4 on 2020-04-21 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200420_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 9, 30, 38, 434368), verbose_name='date published'),
        ),
    ]
