# Generated by Django 2.2.4 on 2020-04-24 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200421_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 12, 57, 15, 948117), verbose_name='date published'),
        ),
    ]
